import string
import random

def generar_telefono():
    digitos_aleatorios = [str(random.randint(0, 9)) for _ in range(7)]
    numero_telefono = '7' + ''.join(digitos_aleatorios)
    return numero_telefono

def obtener_siglas(cadena_texto):
    palabras = cadena_texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    siglas_unidas = "".join(iniciales)
    siglas_finales = siglas_unidas.upper()
    return siglas_finales

def generar_email_aleatorio(usuario):
    dominios_email = ['@gmail.com', '@outlook.com', '@hotmail.com', '@eco.org.bo', '@medioambiente.bo']
    username = usuario.lower().replace(' ', '_').replace('ñ', 'n')
    email_aleatorio = username + random.choice(dominios_email)
    return email_aleatorio

def generar_ubicacion_aleatoria():
    zonas = [
        "Centro", "Sopocachi", "Miraflores", "San Pedro", "Calacoto",
        "Achumani", "Obrajes", "Zona Sur", "Villa Fátima", "El Tejar",
        "Cota Cota", "San Miguel", "Irpavi", "Mallasa", "Mallasilla",
        "Següencoma", "San Antonio", "Pura Pura", "Vino Tinto", "San Jorge",
        "Tembladerani", "Alto Sopocachi", "Pasankeri", "Bajo Sopocachi", "Ciudadela Ferroviaria",
        "Achachicala", "Chuquiaguillo", "Llojeta", "Callapa", "Aranjuez"
    ]
    avenidas = [
        "16 de Julio", "Arce", "Saavedra", "Montes", "Busch",
        "Hernando Siles", "Costanera", "Libertador", "América", "Landaeta",
        "Mariscal Santa Cruz", "Camacho", "Illimani", "Bustamante", "Perú",
        "Brasil", "Del Poeta", "República", "Las Américas", "Argentina",
        "Washington", "6 de Agosto", "Bolívar", "Héctor Ormachea", "Fray Saracho",
        "Guillermo Franco", "Buenos Aires", "Simón Bolívar", "Jaime Mendoza", "Estado Plurinacional"
    ]

    zona_elegida = random.choice(zonas)
    avenida_elegida = random.choice(avenidas)
    numero_puerta = random.randint(1, 999)
    ubicacion_aleatoria = (
        f"Zona {zona_elegida}, Avenida {avenida_elegida} N {numero_puerta}"
    )

    return ubicacion_aleatoria


gobernaciones = [
    {
        'nombre': 'Gobernación de La Paz',
        'sigla': 'GDL',
        'telefono': '22812345',
        'ubicacion': 'Av. Mariscal Santa Cruz, Edificio Central, La Paz',
        'email': 'contacto@lapaz.gob.bo',
        'nombre_autoridad': 'Juan Carlos Aguilar',
        'departamento': 'La Paz',
        'num_provincias': 20,
        'superficies': 133985.0
    },
    {
        'nombre': 'Gobernación de Santa Cruz',
        'sigla': 'GDSC',
        'telefono': '33567890',
        'ubicacion': 'Av. Omar Chávez Ortiz, Santa Cruz de la Sierra',
        'email': 'contacto@santacruz.gob.bo',
        'nombre_autoridad': 'Luis Fernando Camacho',
        'departamento': 'Santa Cruz',
        'num_provincias': 15,
        'superficies': 370621.0
    },
    {
        'nombre': 'Gobernación de Cochabamba',
        'sigla': 'GDC',
        'telefono': '42567891',
        'ubicacion': 'Plaza Colón, Edificio Gobernación, Cochabamba',
        'email': 'contacto@cochabamba.gob.bo',
        'nombre_autoridad': 'Humberto Sánchez',
        'departamento': 'Cochabamba',
        'num_provincias': 16,
        'superficies': 55531.0
    },
    {
        'nombre': 'Gobernación de Oruro',
        'sigla': 'GDO',
        'telefono': '52812347',
        'ubicacion': 'Calle Presidente Montes, Oruro',
        'email': 'contacto@oruro.gob.bo',
        'nombre_autoridad': 'Jhonny Vedia Rodríguez',
        'departamento': 'Oruro',
        'num_provincias': 16,
        'superficies': 53588.0
    },
    {
        'nombre': 'Gobernación de Potosí',
        'sigla': 'GDP',
        'telefono': '63812348',
        'ubicacion': 'Calle Bolívar esquina Ayacucho, Potosí',
        'email': 'contacto@potosi.gob.bo',
        'nombre_autoridad': 'Marco Copa',
        'departamento': 'Potosí',
        'num_provincias': 16,
        'superficies': 118218.0
    },
    {
        'nombre': 'Gobernación de Chuquisaca',
        'sigla': 'GDCQ',
        'telefono': '46456789',
        'ubicacion': 'Plaza 25 de Mayo, Sucre',
        'email': 'contacto@chuquisaca.gob.bo',
        'nombre_autoridad': 'Damián Condori',
        'departamento': 'Chuquisaca',
        'num_provincias': 10,
        'superficies': 51424.0
    },
    {
        'nombre': 'Gobernación de Tarija',
        'sigla': 'GDT',
        'telefono': '46678901',
        'ubicacion': 'Av. La Madrid, Tarija',
        'email': 'contacto@tarija.gob.bo',
        'nombre_autoridad': 'Oscar Montes',
        'departamento': 'Tarija',
        'num_provincias': 6,
        'superficies': 37623.0
    },
    {
        'nombre': 'Gobernación de Beni',
        'sigla': 'GDB',
        'telefono': '38812346',
        'ubicacion': 'Calle Bolívar, Trinidad',
        'email': 'contacto@beni.gob.bo',
        'nombre_autoridad': 'Alejandro Unzueta',
        'departamento': 'Beni',
        'num_provincias': 8,
        'superficies': 213564.0
    },
    {
        'nombre': 'Gobernación de Pando',
        'sigla': 'GDPD',
        'telefono': '38212349',
        'ubicacion': 'Av. 9 de Febrero, Cobija',
        'email': 'contacto@pando.gob.bo',
        'nombre_autoridad': 'Regis Germán Richter',
        'departamento': 'Pando',
        'num_provincias': 5,
        'superficies': 63927.0
    }
]

municipios = [
    'Sucre',
    'Yotala',
    'Poroma',
    'Azurduy',
    'Tarvita',
    'Villa Zudáñez',
    'Presto',
    'Villa Mojocoya',
    'Icla',
    'Padilla',
    'Tomina',
    'Sopachuy',
    'Villa Alcalá',
    'El Villar',
    'Monteagudo',
    'Huacareta',
    'Tarabuco',
    'Yamparáez',
    'Camargo',
    'San Lucas',
    'Incahuasi',
    'Villa Charcas',
    'Villa Serrano',
    'Villa Abecia',
    'Culpina',
    'Las Carreras',
    'Villa Vaca Guzmán (Muyupampa)',
    'Huacaya',
    'Macharetí',
    'La Paz',
    'Palca',
    'Mecapaca',
    'Achocalla',
    'El Alto',
    'Achacachi',
    'Ancoraimes',
    'Chua Cocani',
    'Huarina',
    'Santiago de Huata',
    'Huatajata',
    'Coro Coro',
    'Caquiaviri',
    'Calacoto',
    'Comanche',
    'Charaña',
    'Waldo Ballivián',
    'Nazacara de Pacajes',
    'Callapa',
    'Puerto Acosta',
    'Mocomoco',
    'Puerto Carabuco',
    'Humanata',
    'Escoma',
    'Chuma',
    'Ayata',
    'Aucapata',
    'Sorata',
    'Guanay',
    'Tacacoma',
    'Quiabaya',
    'Combaya',
    'Tipuani',
    'Mapiri',
    'Teoponte',
    'Apolo',
    'Pelechuco',
    'Viacha',
    'Guaqui',
    'Tiahuanaco',
    'Desaguadero',
    'San Andrés de Machaca',
    'Jesús de Machaca',
    'Taraco',
    'Luribay',
    'Sapahaqui',
    'Yaco',
    'Malla',
    'Cairoma',
    'Inquisivi',
    'Quime',
    'Cajuata',
    'Colquiri',
    'Ichoca',
    'Licoma Pampa',
    'Chulumani',
    'Irupana',
    'Yanacachi',
    'Palos Blancos',
    'La Asunta',
    'Pucarani',
    'Laja',
    'Batallas',
    'Puerto Pérez',
    'Sica Sica',
    'Umala',
    'Ayo Ayo',
    'Calamarca',
    'Patacamaya',
    'Colquencha',
    'Collana',
    'Coroico',
    'Coripata',
    'Ixiamas',
    'San Buenaventura',
    'Charazani',
    'Curva',
    'Copacabana',
    'San Pedro de Tiquina',
    'Tito Yupanqui',
    'San Pedro de Curahuara',
    'Papel Pampa',
    'Chacarilla',
    'Santiago de Machaca',
    'Catacora',
    'Caranavi',
    'Alto Beni',
    'Cochabamba',
    'Aiquile',
    'Pasorapa',
    'Omereque',
    'Independencia',
    'Morochata',
    'Cocapata',
    'Tarata',
    'Anzaldo',
    'Arbieto',
    'Sacabamba',
    'Arani',
    'Vacas',
    'Arque',
    'Tacopaya',
    'Capinota',
    'Santiváñez',
    'Sicaya',
    'Cliza',
    'Toco',
    'Tolata',
    'Quillacollo',
    'Sipe Sipe',
    'Tiquipaya',
    'Vinto',
    'Colcapirhua',
    'Sacaba',
    'Colomi',
    'Villa Tunari',
    'Tapacarí',
    'Totora',
    'Pojo',
    'Pocona',
    'Chimoré',
    'Puerto Villarroel',
    'Entre Ríos',
    'Mizque',
    'Vila Vila',
    'Alalay',
    'Punata',
    'Villa Rivero',
    'San Benito',
    'Tacachi',
    'Cuchumuela',
    'Bolívar',
    'Tiraque',
    'Shinahota',
    'Oruro',
    'Caracollo',
    'El Choro',
    'Paria',
    'Challapata',
    'Santuario de Quillacas',
    'Corque',
    'Choquecota',
    'Curahuara de Carangas',
    'Turco',
    'Huachacalla',
    'Escara',
    'Cruz de Machacamarca',
    'Yunguyo de Litoral',
    'Esmeralda',
    'Poopó',
    'Pazña',
    'Antequera',
    'Huanuni',
    'Machacamarca',
    'Salinas de Garci Mendoza',
    'Pampa Aullagas',
    'Sabaya',
    'Coipasa',
    'Chipaya',
    'Toledo',
    'Eucaliptus',
    'Santiago de Andamarca',
    'Belén de Andamarca',
    'Totora',
    'Santiago de Huari',
    'La Rivera',
    'Todos Santos',
    'Carangas',
    'Huayllamarca',
    'Potosí',
    'Tinguipaya',
    'Yocalla',
    'Urmiri',
    'Uncía',
    'Chayanta',
    'Llallagua',
    'Chuquihuta',
    'Betanzos',
    'Chaquí',
    'Tacobamba',
    'Colquechaca',
    'Ravelo',
    'Pocoata',
    'Ocurí',
    'San Pedro de Macha',
    'San Pedro de Buena Vista',
    'Toro Toro',
    'Santiago de Cotagaita',
    'Vitichi',
    'Sacaca',
    'Caripuyo',
    'Tupiza',
    'Atocha',
    'Colcha K',
    'San Pedro de Quemes',
    'San Pablo de Lípez',
    'Mojinete',
    'San Antonio de Esmoruco',
    'Puna',
    'Caiza D',
    'Ckochas',
    'Uyuni',
    'Tomave',
    'Porco',
    'Arampampa',
    'Acasio',
    'Llica',
    'Tahua',
    'Villazón',
    'San Agustín',
    'Tarija',
    'Padcaya',
    'Bermejo',
    'Yacuiba',
    'Caraparí',
    'Villa Montes',
    'Uriondo',
    'Yunchará',
    'San Lorenzo',
    'El Puente',
    'Entre Ríos',
    'Santa Cruz de la Sierra',
    'Cotoca',
    'Porongo',
    'La Guardia',
    'El Torno',
    'Warnes',
    'Okinawa Uno',
    'San Ignacio de Velasco',
    'San Miguel de Velasco',
    'San Rafael de Velasco',
    'Buena Vista',
    'San Carlos',
    'Villa Yapacaní',
    'San Juan de Yapacaní',
    'San José de Chiquitos',
    'Pailón',
    'Roboré',
    'Portachuelo',
    'Santa Rosa del Sara',
    'Colpa Bélgica',
    'Lagunillas',
    'Charagua',
    'Cabezas',
    'Cuevo',
    'Gutiérrez (Kereimba Iyambae)',
    'Camiri',
    'Boyuibe',
    'Vallegrande',
    'El Trigal',
    'Moro Moro',
    'Postrervalle',
    'Pucará',
    'Samaipata',
    'Pampagrande',
    'Mairana',
    'Quirusillas',
    'Montero',
    'General Saavedra',
    'Mineros',
    'Fernández Alonso',
    'San Pedro',
    'Concepción',
    'San Javier',
    'San Ramón',
    'San Julián',
    'San Antonio de Lomerío',
    'Cuatro Cañadas',
    'San Matías',
    'Comarapa',
    'Saipina',
    'Puerto Suárez',
    'Puerto Quijarro',
    'El Carmen Rivero Tórrez',
    'Ascensión de Guarayos',
    'Urubichá',
    'El Puente',
    'Trinidad',
    'San Javier',
    'Riberalta',
    'Guayaramerín',
    'Reyes',
    'San Borja',
    'Santa Rosa',
    'Rurrenabaque',
    'Santa Ana del Yacuma',
    'Exaltación',
    'San Ignacio de Moxos',
    'Loreto',
    'San Andrés',
    'San Joaquín',
    'San Ramón',
    'Puerto Siles',
    'Magdalena',
    'Baures',
    'Huacaraje',
    'Cobija',
    'Porvenir',
    'Bolpebra',
    'Bella Flor',
    'Puerto Rico',
    'San Pedro',
    'Filadelfia',
    'Puerto Gonzalo Moreno',
    'San Lorenzo',
    'Sena',
    'Santa Rosa del Abuná',
    'Ingavi',
    'Nueva Esperanza',
    'Villa Nueva',
    'Santos Mercado'
]
apellidos = [
    'Torres',
    'Iturraldechinel',
    'Iberia',
    'Uriburucabero',
    'Vargas',
    'Zalles',
    'Ruiz',
    'Salinas',
    'Rojas',
    'Romero',
    'Cabrera',
    'Pacheco',
    'Rodriguez',
    'Decabrera',
    'Patino',
    'Aguirreuriondo',
    'Arce',
    'Aparicio',
    'Quiroga',
    'Iturralde',
    'Guerrero',
    'Hurtadodesaracho',
    'Diezdemedina',
    'Flores',
    'Castelo',
    'Saabedra',
    'Moscoso',
    'Daza',
    'Delatorre',
    'Otero',
    'Ychaso',
    'Estrada',
    'Miranda',
    'Baca',
    'Canedobueno',
    'Riverotorres',
    'Aramayo',
    'Picard',
    'Medeirosquerejazu',
    'Rivera',
    'Segovia',
    'Molina',
    'Arze',
    'Detorres',
    'Fernandez',
    'Lealdeayala',
    'Rivero',
    'Villarroel',
    'Zamora',
    'Aguilera',
    'Castillo',
    'Castellanosaparicio',
    'Morales',
    'Tapia',
    'Trigo',
    'Caballero',
    'Mercado',
    'Ortiz',
    'Ramallo',
    'Ruiziideorellana',
    'Sanchez',
    'Urioste',
    'Granier',
    'Torrico',
    'Velasco',
    'Barrientos',
    'Mendoza',
    'Ramos',
    'Angulo',
    'Delcastillo',
    'Guerra',
    'Palacios',
    'Pizarroarce',
    'Reyes',
    'Dearce',
    'Sisa',
    'Calvo',
    'Carrasco',
    'Castro',
    'Deaguilar',
    'Rocha',
    'Saavedra',
    'Tejada',
    'Camacho',
    'Delemoine',
    'Lescano',
    'Lopez',
    'Salazar',
    'Urquidi',
    'Arenas',
    'Gutierrez',
    'Delizarazu',
    'Manriquedelara',
    'Segarradelasroelas',
    'Vega',
    'Lalonde',
    'Mealla',
    'Maldonado',
    'Paz'
]
nombres_masculinos = [
    'Benjamín',
    'Bautista',
    'Felipe',
    'Valentino',
    'Benicio',
    'Juan Carlos',
    'José Luis',
    'Marco Antonio',
    'Miguel Ángel',
    'Juan',
    'Mateo',
    'Agustín',
    'Benjamín',
    'Joaquín',
    'Vicente',
    'Santiago',
    'Matías',
    'Samuel',
    'Jerónimo',
    'Emmanuel',
    'Dylan',
    'Luis',
    'José',
    'Juan',
    'Thiago',
    'Ramón',
    'Juan',
    'José',
    'Antonio',
    'Carlos',
    'Thiago',
    'Liam',
    'Dylan',
    'Luis',
    'Juan',
    'Benjamín',
    'Mateo',
    'Santino',
    'Thiago',
    'Joaquín',
    'Alejandro',
    'Diego',
    'Gabriel',
    'Samuel',
    'Santiago'
]
nombres_femeninos = [
    'Isabella',
    'Martina',
    'Catalina',
    'Sofía',
    'Olivia',
    'Martha',
    'Roxana',
    'Ana María',
    'Elizabeth',
    'Sonia',
    'Sofía',
    'Agustina',
    'Emilia',
    'Isidora',
    'Florencia',
    'Salomé',
    'Isabella',
    'Mariana',
    'Gabriela',
    'María',
    'Emily',
    'Danna',
    'Mía',
    'Domenica',
    'Elizabeth',
    'Beatriz',
    'Ramona',
    'Liz',
    'Camila',
    'Briana',
    'María',
    'Mía',
    'Sofía',
    'Martina',
    'Mía',
    'Emma',
    'Camila',
    'Sofía',
    'Valentina',
    'Isabella',
    'Victoria'
]
def generar_nombre_completo_aleatorio():
    nombre = random.choice(random.choice([nombres_masculinos, nombres_femeninos]))
    paterno = random.choice(apellidos)
    materno = random.choice(apellidos)
    
    return nombre + ' ' + paterno + ' ' + materno

def generar_coordenadas():
    lat = round(random.uniform(-22.0, -9.0), 6)   # Latitudes típicas de Bolivia
    lon = round(random.uniform(-69.0, -57.0), 6)  # Longitudes típicas de Bolivia
    return f"{lat}, {lon}"

def generar_superficie():
    return round(random.uniform(10.0, 5000.0), 2)  # Superficie en hectáreas
